//! Generates FTG constants from `_mkb/constants.json`.
//!
//! One home per fact: no MKB value is ever retyped into a `.rs` file.

use std::{env, fs, path::PathBuf};

fn main() {
    let mkb = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../_mkb/constants.json")
        .canonicalize()
        .expect("_mkb/constants.json not found - the MKB is required to build NEOS");

    println!("cargo:rerun-if-changed={}", mkb.display());

    let raw = fs::read_to_string(&mkb).expect("failed to read constants.json");
    let j: serde_json::Value = serde_json::from_str(&raw).expect("constants.json is not valid JSON");

    let num = |path: &[&str]| -> f64 {
        let mut cur = &j;
        for k in path {
            cur = cur
                .get(k)
                .unwrap_or_else(|| panic!("constants.json missing key path {path:?}"));
        }
        cur.as_f64()
            .unwrap_or_else(|| panic!("constants.json value at {path:?} is not a number"))
    };

    let carrier = num(&["constants", "baseline_carrier_frequency", "value"]);
    let phase_false = num(&["logic_phases", "false_equivalent"]);
    let phase_true = num(&["logic_phases", "true_equivalent"]);
    let lock_bound = num(&["thresholds", "link_stability_phase_variance", "value"]);
    let teardown = num(&["thresholds", "teardown_phase_shift", "value"]);

    // Teardown is an exact pi inversion. A drifted value would make cancellation
    // partial, and the residual would show up as a mysterious tolerance failure
    // in Test Case 1 rather than as a clear cause.
    assert!(
        (teardown - std::f64::consts::PI).abs() < 1e-12,
        "teardown_phase_shift is {teardown}, expected pi. Phase Inversion Teardown \
         requires an exact pi shift - see _mkb/equations.md."
    );

    let generated = format!(
        r#"// @generated by build.rs from _mkb/constants.json - DO NOT EDIT.

/// Baseline carrier `omega_c`, rad/s. Also the multiplexing fundamental.
pub const CARRIER_RAD_PER_SEC: f64 = {carrier:?};

/// Axiom A2: phase for a zero bit, `-pi/2`.
pub const PHASE_FALSE: f64 = {phase_false:?};

/// Axiom A2: phase for a one bit, `+pi/2`.
pub const PHASE_TRUE: f64 = {phase_true:?};

/// Handshake bound: phase variance must be STRICTLY below this to resonate.
pub const LINK_LOCK_BOUND: f64 = {lock_bound:?};

/// Phase Inversion Teardown shift. Exactly pi.
pub const TEARDOWN_PHASE_SHIFT: f64 = {teardown:?};
"#
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mkb_constants.rs");
    fs::write(&out, generated).expect("failed to write generated constants");
}
