//! Generates kernel constants from `_mkb/constants.json`.
//!
//! One home per fact: no MKB value is ever retyped into a `.rs` file.

use std::{env, fs, path::PathBuf};

fn main() {
    let mkb = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../_mkb/constants.json")
        .canonicalize()
        .expect("_mkb/constants.json not found — the MKB is required to build NEOS");

    println!("cargo:rerun-if-changed={}", mkb.display());

    let raw = fs::read_to_string(&mkb).expect("failed to read constants.json");
    let j: serde_json::Value = serde_json::from_str(&raw).expect("constants.json is not valid JSON");

    let num = |path: &[&str]| -> f64 {
        let mut cur = &j;
        for k in path {
            cur = cur
                .get(k)
                .unwrap_or_else(|| panic!("constants.json missing key path {path:?}"));
        }
        cur.as_f64()
            .unwrap_or_else(|| panic!("constants.json value at {path:?} is not a number"))
    };

    let c_h = num(&["constants", "howard_comma", "value"]);
    let xi_ref = num(&["resonance", "xi_at_reference", "value"]);
    let xi_sup = num(&["resonance", "xi_upper_bound", "value"]);
    let diffusion = num(&["resonance", "diffusion_stability_factor", "value"]);
    let phase_false = num(&["logic_phases", "false_equivalent"]);
    let phase_true = num(&["logic_phases", "true_equivalent"]);
    let band = num(&["gates", "resonance_band", "value"]);
    let teardown = num(&["thresholds", "teardown_phase_shift", "value"]);
    let link_variance = num(&["thresholds", "link_stability_phase_variance", "value"]);

    // The band is derived, not independent: it is the link-stability variance
    // over one mean period, i.e. (pi/4)/(2*pi). If someone edits one without
    // the other, the standing-wave criterion the two share has been broken and
    // the build must stop rather than ship two disagreeing thresholds.
    let derived = link_variance / (2.0 * std::f64::consts::PI);
    assert!(
        (derived - band).abs() <= f64::EPSILON,
        "gates.resonance_band is {band}, but link_stability_phase_variance/(2*pi) \
         is {derived}. These are the same criterion — see _mkb/gates.md 3.3."
    );

    // C_H pairs with ordinary frequency. If the JSON ever says otherwise the
    // build must stop rather than silently scale every energy by 2*pi.
    let freq_var = j["constants"]["howard_comma"]["frequency_variable"]
        .as_str()
        .expect("howard_comma must declare its frequency_variable");
    assert_eq!(
        freq_var, "nu",
        "howard_comma.frequency_variable is {freq_var:?}, expected \"nu\". \
         C_H pairs with ordinary frequency — see _mkb/reconciliation.md R5a."
    );

    let generated = format!(
        r#"// @generated by build.rs from _mkb/constants.json — DO NOT EDIT.

/// Howard Comma: the quantum computational unit, `h / sqrt(2*pi)`.
///
/// Pairs with ORDINARY frequency: `E = C_H * nu`. Neither `h` nor `hbar`.
pub const HOWARD_COMMA: f64 = {c_h:?};

/// `xi(R) = 1` exactly — the resonance correction is unity at reference scale.
pub const XI_AT_REFERENCE: f64 = {xi_ref:?};

/// Supremum of `xi(r)`, `e / sinh(1)`, approached as `r -> 0`.
pub const XI_SUPREMUM: f64 = {xi_sup:?};

/// The `2` in the load-balancer stability bound `alpha < 2 / lambda_max(L)`.
pub const DIFFUSION_STABILITY_FACTOR: f64 = {diffusion:?};

/// Axiom A2: the phase standing in for classical `false`, `-pi/2`.
pub const PHASE_FALSE: f64 = {phase_false:?};

/// Axiom A2: the phase standing in for classical `true`, `+pi/2`.
pub const PHASE_TRUE: f64 = {phase_true:?};

/// Sustained-resonance detuning limit, `1/8`.
///
/// Derived in `_mkb/gates.md` 3.3 as `(pi/4)/(2*pi)`: relative phase drift over
/// one period of the mean effective frequency, held inside the standing-wave
/// stability variance. Relative by derivation, not by choice.
pub const RESONANCE_BAND: f64 = {band:?};

/// The exact `pi` shift of Phase Inversion Teardown.
///
/// Also the separation between A2's two orientations, which is what makes the
/// shift an involution on the permitted set. See `_mkb/gates.md` 2.1.
pub const PHASE_INVERSION_SHIFT: f64 = {teardown:?};
"#
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mkb_constants.rs");
    fs::write(&out, generated).expect("failed to write generated constants");
}
