//! Generates Rust constants from `_mkb/constants.json`.
//!
//! This is the mechanism that keeps one home per fact: no numeric value from
//! the Mathematical Knowledge Base is ever retyped into a `.rs` file. If a
//! value changes in the JSON, it changes here on the next build.
//!
//! See `_mkb/CONTEXT.md` — the MKB is the law, and code is downstream of it.

use std::{env, fs, path::PathBuf};

fn main() {
    let mkb = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../_mkb/constants.json")
        .canonicalize()
        .expect("_mkb/constants.json not found — the MKB is required to build NEOS");

    println!("cargo:rerun-if-changed={}", mkb.display());

    let raw = fs::read_to_string(&mkb).expect("failed to read constants.json");
    let j: serde_json::Value = serde_json::from_str(&raw).expect("constants.json is not valid JSON");

    // Pull each value by its documented JSON path. A missing key is a hard
    // error: silently defaulting would let code drift from the law.
    let num = |path: &[&str]| -> f64 {
        let mut cur = &j;
        for k in path {
            cur = cur
                .get(k)
                .unwrap_or_else(|| panic!("constants.json missing key path {:?}", path));
        }
        cur.as_f64()
            .unwrap_or_else(|| panic!("constants.json value at {:?} is not a number", path))
    };
    let int = |path: &[&str]| -> u32 {
        let mut cur = &j;
        for k in path {
            cur = cur
                .get(k)
                .unwrap_or_else(|| panic!("constants.json missing key path {:?}", path));
        }
        cur.as_u64()
            .unwrap_or_else(|| panic!("constants.json value at {:?} is not an integer", path)) as u32
    };

    let lambda = num(&["operators", "otimes_scale_lambda", "value"]);
    let domain_max = num(&["operators", "otimes_domain_max_product", "value"]);
    let curvature = num(&["constants", "hyperbolic_curvature", "value"]);
    let scale_r = num(&["scales", "lattice_scale_R", "value"]);
    let vertex_degree = int(&["tessellation", "vertex_degree"]);

    let schlafli = j["tessellation"]["schlafli"]
        .as_array()
        .expect("tessellation.schlafli must be an array");
    let p = schlafli[0].as_u64().unwrap() as u32;
    let q = schlafli[1].as_u64().unwrap() as u32;

    // The notation and the vertex-degree field must agree. vACUUM_FLUX.pdf
    // contradicted itself here (see _mkb/reconciliation.md R3); this check
    // makes sure the resolution cannot silently regress in the JSON.
    assert_eq!(
        q, vertex_degree,
        "constants.json inconsistent: schlafli {{{p},{q}}} implies vertex degree {q}, \
         but tessellation.vertex_degree is {vertex_degree}. See _mkb/reconciliation.md R3."
    );

    let generated = format!(
        r#"// @generated by build.rs from _mkb/constants.json — DO NOT EDIT.
// Change the JSON, not this file. See _mkb/CONTEXT.md.

/// Pinned ratio l_P/r for the modified multiplication operator.
/// Chosen as arcsinh(1) so that `1 (x) 1 = 2` holds bit-exactly.
pub const OTIMES_LAMBDA: f64 = {lambda:?};

/// Hard domain limit: `a*b` must stay below this or sinh overflows f64.
pub const OTIMES_DOMAIN_MAX_PRODUCT: f64 = {domain_max:?};

/// Gaussian curvature in lattice-native units.
pub const CURVATURE_K: f64 = {curvature:?};

/// Lattice-native scale. R = 1 is what makes K = -1/R^2 = -1.
pub const LATTICE_SCALE_R: f64 = {scale_r:?};

/// Schlafli symbol {{p, q}}: p-gons, q meeting at each vertex.
pub const SCHLAFLI: (u32, u32) = ({p}, {q});

/// Number of cells meeting at each vertex. Four, per reconciliation R3.
pub const VERTEX_DEGREE: u32 = {vertex_degree};

/// Edges per cell — equal to p.
pub const EDGES_PER_CELL: u32 = {p};
"#
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mkb_constants.rs");
    fs::write(&out, generated).expect("failed to write generated constants");
}
