//! Generates substrate constants from `_mkb/constants.json`.
//!
//! One home per fact: no MKB value is ever retyped into a `.rs` file.

use std::{env, fs, path::PathBuf};

fn main() {
    let mkb = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../_mkb/constants.json")
        .canonicalize()
        .expect("_mkb/constants.json not found - the MKB is required to build NEOS");

    println!("cargo:rerun-if-changed={}", mkb.display());

    let raw = fs::read_to_string(&mkb).expect("failed to read constants.json");
    let j: serde_json::Value = serde_json::from_str(&raw).expect("constants.json is not valid JSON");

    let num = |path: &[&str]| -> f64 {
        let mut cur = &j;
        for k in path {
            cur = cur
                .get(k)
                .unwrap_or_else(|| panic!("constants.json missing key path {path:?}"));
        }
        cur.as_f64()
            .unwrap_or_else(|| panic!("constants.json value at {path:?} is not a number"))
    };

    let carrier = num(&["constants", "baseline_carrier_frequency", "value"]);
    let curvature = num(&["constants", "hyperbolic_curvature", "value"]);
    let phase_false = num(&["logic_phases", "false_equivalent"]);
    let phase_true = num(&["logic_phases", "true_equivalent"]);
    let otimes_max = num(&["operators", "otimes_domain_max_product", "value"]);

    // The carrier is an ANGULAR frequency. If the MKB ever reclassifies it,
    // the build must stop rather than let it reach E = C_H * nu.
    let units = j["constants"]["baseline_carrier_frequency"]["units"]
        .as_str()
        .expect("baseline_carrier_frequency must declare units");
    assert_eq!(
        units, "rad/s",
        "baseline_carrier_frequency units are {units:?}, expected \"rad/s\". \
         omega_c is angular - see _mkb/reconciliation.md R5a."
    );

    let generated = format!(
        r#"// @generated by build.rs from _mkb/constants.json - DO NOT EDIT.

/// Baseline carrier, `omega_c`. ANGULAR frequency, rad/s.
pub const CARRIER_RAD_PER_SEC: f64 = {carrier:?};

/// Gaussian curvature in lattice-native units.
pub const CURVATURE_K: f64 = {curvature:?};

/// Axiom A2: phase standing in for classical `false`, `-pi/2`.
pub const PHASE_FALSE: f64 = {phase_false:?};

/// Axiom A2: phase standing in for classical `true`, `+pi/2`.
pub const PHASE_TRUE: f64 = {phase_true:?};

/// Hard domain limit on the `(x)` operator, used by pool splitting.
pub const OTIMES_DOMAIN_MAX_PRODUCT: f64 = {otimes_max:?};
"#
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mkb_constants.rs");
    fs::write(&out, generated).expect("failed to write generated constants");
}
