//! Generates crystallisation constants from `_mkb/constants.json`.
//!
//! One home per fact: the JSON is the single source, and each crate reads it
//! directly rather than depending on another crate for a number.

use std::{env, fs, path::PathBuf};

fn main() {
    let mkb = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../_mkb/constants.json")
        .canonicalize()
        .expect("_mkb/constants.json not found - the MKB is required to build NEOS");

    println!("cargo:rerun-if-changed={}", mkb.display());

    let raw = fs::read_to_string(&mkb).expect("failed to read constants.json");
    let j: serde_json::Value = serde_json::from_str(&raw).expect("constants.json is not valid JSON");

    let c_h = j["constants"]["howard_comma"]["value"]
        .as_f64()
        .expect("constants.howard_comma.value must be a number");

    // The time-crystal quantisation uses E = C_H * nu with ORDINARY frequency.
    // If the MKB ever repairs C_H to the angular convention, the Floquet
    // quasi-energies here would silently shift by 2*pi.
    let freq_var = j["constants"]["howard_comma"]["frequency_variable"]
        .as_str()
        .expect("howard_comma must declare its frequency_variable");
    assert_eq!(
        freq_var, "nu",
        "howard_comma.frequency_variable is {freq_var:?}, expected \"nu\" - \
         see _mkb/reconciliation.md R5a."
    );

    let generated = format!(
        r#"// @generated by build.rs from _mkb/constants.json - DO NOT EDIT.

/// Howard Comma, `h / sqrt(2*pi)`. The quantisation step for Floquet
/// quasi-energies and phase-space action. Pairs with ORDINARY frequency.
pub const HOWARD_COMMA: f64 = {c_h:?};
"#
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mkb_constants.rs");
    fs::write(&out, generated).expect("failed to write generated constants");
}
