/*
 * media_ffi.h — the C header for NEOS's media FFI bridge.
 *
 * Hand-written, verified against neos/media_ffi/src/lib.rs by actually
 * compiling and running a real C program against the built library — see
 * neos/media_ffi/ffi_test/main.c. Not generated by a tool (e.g. cbindgen);
 * a real, stated risk of that choice is that this header can drift from the
 * Rust signatures if one changes without the other being updated by hand.
 *
 * MediaFfiImageResult is opaque on purpose: this header never describes its
 * fields, only its existence. Call the accessor functions below to read it;
 * never assume anything about its layout or size.
 */

#ifndef NEOS_MEDIA_FFI_H
#define NEOS_MEDIA_FFI_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct MediaFfiImageResult MediaFfiImageResult;

/* Decode a real PPM image (bytes, len bytes long) and crystallise it
 * through the holographic pipeline. Returns a valid, freeable handle on
 * both success and crystallisation-level failure — check
 * media_ffi_image_result_is_ok() first. Returns NULL only if bytes itself
 * is NULL. */
MediaFfiImageResult *media_ffi_crystallise_image(const unsigned char *bytes, size_t len);

/* 1 if result holds a real crystallised image, 0 if it holds an error (or
 * result itself is NULL). */
int media_ffi_image_result_is_ok(const MediaFfiImageResult *result);

/* The error message as a NUL-terminated string, or NULL if result is ok or
 * is itself NULL. Borrowed from result — valid until result is freed, never
 * freed separately. */
const char *media_ffi_image_result_error_message(const MediaFfiImageResult *result);

/* How many faces result holds — 4 on success, 0 on error or a NULL
 * result. */
size_t media_ffi_image_result_face_count(const MediaFfiImageResult *result);

/* A face's total energy, or NAN (check with isnan() from <math.h>) if
 * result is NULL/an error, or face is out of range. */
double media_ffi_image_result_face_energy(const MediaFfiImageResult *result, size_t face);

/* How many frequency coefficients a face holds, or 0 if result/face is
 * invalid. */
size_t media_ffi_image_result_coefficient_count(const MediaFfiImageResult *result, size_t face);

/* Read one complex coefficient through the two output pointers. Writes
 * *out_re/*out_im and returns 1 on success; returns 0 and leaves the
 * out-pointers untouched on any failure. */
int media_ffi_image_result_coefficient(
    const MediaFfiImageResult *result,
    size_t face,
    size_t index,
    double *out_re,
    double *out_im
);

/* Release a handle returned by media_ffi_crystallise_image(). Tolerates a
 * NULL pointer as a no-op, matching C's own free(NULL). Never call this
 * twice on the same handle. */
void media_ffi_image_result_free(MediaFfiImageResult *result);

#ifdef __cplusplus
}
#endif

#endif /* NEOS_MEDIA_FFI_H */
