//! Generates GUI constants from `_mkb/constants.json`.
//!
//! One home per fact: no MKB value is ever retyped into a `.rs` file.

use std::{env, fs, path::PathBuf};

fn main() {
    let mkb = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../_mkb/constants.json")
        .canonicalize()
        .expect("_mkb/constants.json not found - the MKB is required to build NEOS");

    println!("cargo:rerun-if-changed={}", mkb.display());

    let raw = fs::read_to_string(&mkb).expect("failed to read constants.json");
    let j: serde_json::Value = serde_json::from_str(&raw).expect("constants.json is not valid JSON");

    let num = |path: &[&str]| -> f64 {
        let mut cur = &j;
        for k in path {
            cur = cur
                .get(k)
                .unwrap_or_else(|| panic!("constants.json missing key path {path:?}"));
        }
        cur.as_f64()
            .unwrap_or_else(|| panic!("constants.json value at {path:?} is not a number"))
    };

    let curvature = num(&["constants", "hyperbolic_curvature", "value"]);
    let scale_r = num(&["scales", "lattice_scale_R", "value"]);

    // The geodesic construction and the ball<->hyperboloid charts are written
    // for K = -1. At any other curvature they are simply wrong, and the failure
    // would be a subtly misshapen scene rather than an error.
    assert!(
        (curvature + 1.0).abs() < 1e-12,
        "hyperbolic_curvature is {curvature}, expected -1.0. The renderer's \
         geodesics assume lattice-native units - see _mkb/reconciliation.md R2."
    );

    let generated = format!(
        r#"// @generated by build.rs from _mkb/constants.json - DO NOT EDIT.

/// Gaussian curvature in lattice-native units. The geodesic construction
/// assumes this is exactly -1.
pub const CURVATURE_K: f64 = {curvature:?};

/// Lattice-native scale, used by the node standing wave `psi(r)`.
pub const LATTICE_SCALE_R: f64 = {scale_r:?};
"#
    );

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mkb_constants.rs");
    fs::write(&out, generated).expect("failed to write generated constants");
}
